name: Deploy Binaries to Pages

on:
  workflow_run:
    workflows: ["Build and Release Binary"]
    types:
      - completed
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: '要部署的分支名称'
        required: true
        default: 'develop'
        type: choice
        options:
          - main
          - develop

# 设置GITHUB_TOKEN的权限
permissions:
  contents: write
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 调试工作流信息
  debug-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 打印工作流信息
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Triggering workflow: ${{ github.event.workflow.name || 'N/A' }}"
          
          # 如果是workflow_run事件，打印相关信息
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
            echo "Workflow run id: ${{ github.event.workflow_run.id }}"
          fi

          # 如果是workflow_dispatch事件，打印相关信息
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Selected branch: ${{ github.event.inputs.branch }}"
          fi

  # 发布到主分支页面
  deploy-main:
    needs: debug-workflow
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download neko-status artifacts
        uses: actions/download-artifact@v4
        with:
          name: neko-status-latest
          path: download
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Prepare public directory
        run: |
          mkdir -p public
          
          # 复制二进制文件到public目录
          cp download/neko-status_linux_amd64 public/
          cp download/neko-status_linux_arm64 public/
          cp download/neko-status_linux_arm7 public/
          cp download/neko-status_linux_386 public/
          cp download/neko-status_darwin_amd64 public/
          cp download/neko-status_darwin_arm64 public/
          cp download/neko-status_linux_universal public/neko-status
          cp download/neko-status_darwin_universal public/neko-status_darwin
          cp download/SHA256SUMS public/
          
          # 创建版本信息文件
          echo "$(date +%Y-%m-%d_%H:%M:%S)" > public/version.txt
          
          # 确保文件可执行
          chmod +x public/neko-status*
          
          # 列出文件
          ls -la public/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  # 发布到开发分支页面
  deploy-dev:
    needs: debug-workflow
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.branch == 'develop' || github.ref == 'refs/heads/develop')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: 打印构件下载信息
        run: |
          echo "尝试从以下运行ID下载构件: ${{ github.event.workflow_run.id || 'manual trigger' }}"
          echo "仓库: ${{ github.repository }}"
          echo "分支: ${{ github.event.workflow_run.head_branch || github.ref }}"
      
      - name: 获取最新的workflow运行ID
        id: get-run-id
        if: github.event_name == 'workflow_dispatch'
        run: |
          # 使用GitHub CLI获取最新的workflow运行ID
          echo "安装 GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
          # 使用GitHub CLI获取Build and Release Binary workflow的最新成功运行ID
          LATEST_RUN_ID=$(gh run list --workflow "Build and Release Binary" --branch develop --json databaseId,conclusion,headBranch --jq '.[] | select(.conclusion=="success" and .headBranch=="develop") | .databaseId' --limit 1)
          
          if [ -n "$LATEST_RUN_ID" ]; then
            echo "latest_run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
            echo "找到最新的workflow运行ID: $LATEST_RUN_ID"
          else
            echo "未找到成功的workflow运行"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download neko-status-dev artifacts
        uses: actions/download-artifact@v4
        with:
          name: neko-status-dev-latest
          path: download-dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id || steps.get-run-id.outputs.latest_run_id }}
      
      - name: 检查下载的文件
        run: |
          echo "下载目录内容:"
          find download-dev -type f | sort

      - name: Prepare dev directory
        run: |
          mkdir -p public-dev
          ls -la download-dev || echo "download-dev目录内容列表失败"
          
          # 复制二进制文件到public-dev目录
          cp download-dev/neko-status_linux_amd64 public-dev/ || echo "linux_amd64文件不存在"
          cp download-dev/neko-status_linux_arm64 public-dev/ || echo "linux_arm64文件不存在" 
          cp download-dev/neko-status_linux_arm7 public-dev/ || echo "linux_arm7文件不存在"
          cp download-dev/neko-status_linux_386 public-dev/ || echo "linux_386文件不存在"
          cp download-dev/neko-status_darwin_amd64 public-dev/ || echo "darwin_amd64文件不存在"
          cp download-dev/neko-status_darwin_arm64 public-dev/ || echo "darwin_arm64文件不存在"
          cp download-dev/neko-status_linux_universal public-dev/neko-status || echo "linux_universal文件不存在"
          cp download-dev/neko-status_darwin_universal public-dev/neko-status_darwin || echo "darwin_universal文件不存在"
          cp download-dev/SHA256SUMS public-dev/ || echo "SHA256SUMS文件不存在"
          
          # 创建版本信息文件
          echo "DEV-$(date +%Y-%m-%d_%H:%M:%S)" > public-dev/version.txt
          
          # 确保文件可执行
          find public-dev -type f -name "neko-status*" -exec chmod +x {} \;
          
          # 列出文件
          ls -la public-dev/
      
      - name: Deploy to Dev Folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public-dev
          target-folder: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
